// Mocks generated by Mockito 5.4.0 from annotations
// in project_flutter/test/widget/moedas_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:project_flutter/models/coin.dart' as _i3;
import 'package:project_flutter/repository/coins_controller.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CoinsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoinsController extends _i1.Mock implements _i2.CoinsController {
  MockCoinsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Coin> get selected => (super.noSuchMethod(
        Invocation.getter(#selected),
        returnValue: <_i3.Coin>[],
      ) as List<_i3.Coin>);
  @override
  void updateSelected(_i3.Coin? coin) => super.noSuchMethod(
        Invocation.method(
          #updateSelected,
          [coin],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool isSelected(_i3.Coin? coin) => (super.noSuchMethod(
        Invocation.method(
          #isSelected,
          [coin],
        ),
        returnValue: false,
      ) as bool);
}
